'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,Cloud,CloudOff,Volume2,BookOpen,ChevronLeft,Check,Lock,RotateCcw,X,LoaderCircle,Pause,Headphones} from 'lucide-react';
import {lessons,stages,totalWords,totalSentences,countsFor,questionsFor,progressSchema,errorSchema,type Progress,type Word} from '../lib/course';
import hangul from '../content/hangul.json';

type Props={signedIn:boolean;signInHref:string};
type Panel='lessons'|'plan'|'hangul'|null;
type ToolContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
const empty:Progress={rows:[],currentLesson:'c01',serverTime:0};
const targets=[['第 1 月','韩文拼读与生活表达','800','1,000'],['第 2 月','熟悉日常对话','1,800','2,200'],['第 3 月','叙述经历、说明理由','3,000','3,800'],['第 4 月','社会话题与长句理解','4,200','5,200'],['第 5 月','阅读观点、论证与转述','5,200','6,600'],['第 6 月','综合运用与考试检验','6,000','8,000']];
export default function LearningApp({signedIn,signInHref}:Props){
 const [progress,setProgress]=useState<Progress>(empty);const [loaded,setLoaded]=useState(false);
 const [lessonId,setLessonId]=useState('c01');const [cursor,setCursor]=useState(0);
 const [meaning,setMeaning]=useState(true);const [word,setWord]=useState<Word|null>(null);
 const [panel,setPanel]=useState<Panel>(null);const dialog=useRef<HTMLDialogElement>(null);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const inFlight=useRef(false);
 const [sync,setSync]=useState(signedIn?'正在读取进度':'登录后同步进度');
 const [audioError,setAudioError]=useState('');const [playing,setPlaying]=useState(false);const [rate,setRate]=useState(1);
 const audio=useRef<HTMLAudioElement|null>(null);const audioEpoch=useRef(0);
 const [quizStep,setQuizStep]=useState(0);const [answers,setAnswers]=useState<number[]>([]);const [done,setDone]=useState(false);
 const [draft,setDraft]=useState('');const [draftRevision,setDraftRevision]=useState(0);const [draftSaved,setDraftSaved]=useState(false);
 const initialised=useRef(false);const draftTouched=useRef(false);
 const index=Math.max(0,lessons.findIndex(l=>l.id===lessonId));const lesson=lessons[index];
 const line=lesson.lines[Math.min(cursor,lesson.lines.length-1)];const record=progress.rows.find(r=>r.lesson_id===lessonId);
 const quiz=questionsFor(lesson);const isQuiz=cursor>=lesson.lines.length&&!done;const q=quiz[quizStep];
 const selected=answers[quizStep];const isCorrect=selected===q.answer;
 const counts=countsFor(progress.rows);
 const due=progress.rows.filter(r=>r.next_review_at!==null&&r.next_review_at<=Math.max(progress.serverTime,Date.now()));
 const unlocked=(i:number)=>i===0||!!progress.rows.find(r=>r.lesson_id===lessons[i-1].id)?.completed_at;
 const stopAudio=useCallback(()=>{audioEpoch.current++;audio.current?.pause();audio.current=null;setPlaying(false);},[]);
 const changeView=useCallback((p:Progress,id:string,restart=false)=>{const row=p.rows.find(r=>r.lesson_id===id);setLessonId(id);setCursor(restart?0:row?.cursor??0);setDone(!restart&&!!row?.completed_at&&(row?.cursor??0)>=(lessons.find(l=>l.id===id)?.lines.length??6));setQuizStep(0);setAnswers([]);setWord(null);setDraft(row?.draft??'');setDraftRevision(row?.draft_revision??0);draftTouched.current=false;setDraftSaved(false);setAudioError('');stopAudio();},[stopAudio]);
 const load=useCallback(async(restore=false)=>{
  if(!signedIn){setLoaded(true);return;}
  try{const response=await fetch('/api/progress',{cache:'no-store'});const raw=await response.json();if(!response.ok)throw new Error(errorSchema.parse(raw).error);const data=progressSchema.parse(raw);setProgress(data);setSync('进度已存云端');setError('');setLoaded(true);
   if(restore||!initialised.current){changeView(data,data.currentLesson);initialised.current=true;}
  }catch(e){setLoaded(true);setSync('暂未连接云端');setError(e instanceof Error?e.message:'读取失败，请重试。');}
 },[signedIn,changeView]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible'&&!inFlight.current)void load();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);audio.current?.pause();};},[load]);
 useEffect(()=>{const beforeLeave=(event:BeforeUnloadEvent)=>{if(draftTouched.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeLeave);return()=>window.removeEventListener('beforeunload',beforeLeave);},[]);
 useEffect(()=>{if(panel&&!dialog.current?.open)dialog.current?.showModal();if(!panel&&dialog.current?.open)dialog.current?.close();},[panel]);
 const mutate=async(body:Record<string,unknown>):Promise<Progress|null>=>{
  if(inFlight.current)return null;inFlight.current=true;setBusy(true);setError('');setSync('正在保存…');
  try{const response=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const raw=await response.json();if(!response.ok){const failure=errorSchema.parse(raw);if(failure.progress)setProgress(failure.progress);throw new Error(failure.error);}const data=progressSchema.parse(raw);setProgress(data);setSync('进度已存云端');return data;
  }catch(e){setSync('这一步尚未保存');setError(e instanceof Error?e.message:'保存失败，请再次点击重试。');return null;}
  finally{inFlight.current=false;setBusy(false);}
 };
 const play=async(path:string)=>{
  stopAudio();const epoch=audioEpoch.current;setAudioError('');const player=new Audio(path);audio.current=player;player.playbackRate=rate;player.preservesPitch=true;
  player.onended=()=>{if(epoch===audioEpoch.current)setPlaying(false);};
  player.onerror=()=>{if(epoch===audioEpoch.current){setPlaying(false);setAudioError('音频未能加载，请检查网络后重听。');}};
  try{await player.play();if(epoch===audioEpoch.current)setPlaying(true);}catch{if(epoch===audioEpoch.current){setPlaying(false);setAudioError('播放未成功，请再点一次“听原音”。');}}
 };
 const chooseLesson=async(id:string,restart=false)=>{if(draftTouched.current&&lesson.stage===5){const saved=await mutate({action:'draft',lessonId,text:draft,revision:draftRevision});if(!saved)return;draftTouched.current=false;}stopAudio();const p=await mutate({action:'select',lessonId:id,restart});if(p){changeView(p,id,restart);setPanel(null);setMeaning(!restart);}};
 const nextLine=async()=>{const p=await mutate({action:'read',lessonId,lineIndex:cursor});if(p){stopAudio();setCursor(cursor+1);setWord(null);setAudioError('');}};
 const complete=async()=>{const p=await mutate({action:'complete',lessonId,answers});if(p){stopAudio();setDone(true);}};
 const saveDraft=async()=>{const p=await mutate({action:'draft',lessonId,text:draft,revision:draftRevision});if(p){setDraftRevision(p.rows.find(r=>r.lesson_id===lessonId)?.draft_revision??draftRevision);draftTouched.current=false;setDraftSaved(true);}};
 const stateRef=useRef({lesson,progress,cursor});stateRef.current={lesson,progress,cursor};
 useEffect(()=>{const context=(document as Document&{modelContext?:ToolContext}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const register=async()=>{try{await context.registerTool({name:'read_korean_learning_progress',description:'Read the visible course, current dialogue, cloud learning counts, and unlocked lessons without changing study progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');const s=stateRef.current;return{lessonId:s.lesson.id,title:s.lesson.title,line:s.cursor+1,counts:countsFor(s.progress.rows),completed:s.progress.rows.filter(r=>r.completed_at).map(r=>r.lesson_id)};}},{signal:controller.signal});}catch(e){console.warn('WebMCP unavailable',e);}};void register();return()=>controller.abort();},[]);
 const disabled=busy||!loaded||!signedIn||(!initialised.current&&signedIn);
 return <><header className="topbar"><div className="brand"><span className="mark" aria-hidden="true">한</span><strong>한걸음 <small>一句一步</small></strong></div>{signedIn?<span className="sync" role="status">{busy?<LoaderCircle size={17} className="spin"/>:error?<CloudOff size={17}/>:<Cloud size={17}/>}<span>{sync}</span></span>:<a className="button" href={signInHref} target="_top"><Cloud size={17}/>登录同步</a>}</header>
 <main className="workspace"><aside className="sidebar"><p className="eyebrow">YOUR KOREAN JOURNEY</p><h2>从一句你好开始</h2>{stages.map((s,i)=><button key={s} className={'stage '+(lesson.stage===i?'active':'')} onClick={()=>setPanel('lessons')}><span className="stage-index">{i+1}</span><span>{s}</span>{i<lesson.stage&&<Check size={14}/>}</button>)}<button className="button subtle" onClick={()=>setPanel('hangul')}><BookOpen size={17}/>不会读？先认韩文</button><div className="sidebar-foot"><p>180 天 · 每天 4 小时以上</p><button className="text-link" onClick={()=>setPanel('plan')}>查看半年课程目标</button><p className="small-note">当前首批：36 关<br/>{totalWords} 核心词条 · {totalSentences} 个独立句</p>{due.length>0&&<button className="button" disabled={disabled} onClick={()=>void chooseLesson(due[0].lesson_id,true)}><RotateCcw size={15}/>复习到期对话 · {due.length}</button>}</div></aside>
 <section className="learning"><div className="lesson-heading"><div><p className="eyebrow">CHAPTER {String(lesson.stage+1).padStart(2,'0')} / {stages[lesson.stage]}</p><h1>{lesson.title}</h1></div><button className="pill course-pill" onClick={()=>setPanel('lessons')}>第 {index+1} / {lessons.length} 关 <BookOpen size={14}/></button></div>
 <div className="mobile-tools"><button className="text-link" onClick={()=>setPanel('hangul')}>韩文拼读</button><button className="text-link" onClick={()=>setPanel('plan')}>半年目标</button>{due.length>0&&<button className="text-link" disabled={disabled} onClick={()=>void chooseLesson(due[0].lesson_id,true)}>复习 · {due.length}</button>}</div>
 <div className="progress-track" role="progressbar" aria-label="本关对话进度" aria-valuenow={Math.min(cursor,lesson.lines.length)} aria-valuemin={0} aria-valuemax={lesson.lines.length}><div className="progress-fill" style={{width:Math.min(100,cursor/lesson.lines.length*100)+'%'}}/></div>
 {!signedIn&&<div className="info-banner">用同一个 ChatGPT 账号登录，手机和电脑就能接着学。<a href={signInHref} target="_top">登录并开始</a></div>}
 {error&&<div className="error-state" role="alert">{error} <button className="text-link" disabled={busy} onClick={()=>void load()}>重新连接</button></div>}
 <div className="dialogue-card"><div className="scene-head"><strong>{lesson.scene}</strong><span>{done?'本关完成':isQuiz?'听懂了吗？':`${cursor+1} / ${lesson.lines.length}`}</span></div>
 {done?<div className="dialogue-body"><div className="success-icon"><Check size={27}/></div><h2>又能多聊一个话题了。</h2><p className="translation" style={{marginTop:12}}>这段对话已经完成，学习进度已保存在云端。</p><p className="line-note">下次复习：{record?.next_review_at?new Date(record.next_review_at).toLocaleDateString('zh-CN',{month:'long',day:'numeric'}):'明天'}。复习会沿用同一段对话。</p><div className="completion-actions">{index<lessons.length-1?<button className="button primary" disabled={disabled} onClick={()=>void chooseLesson(lessons[index+1].id)}>进入下一关<ArrowRight size={17}/></button>:<button className="button primary" onClick={()=>setPanel('plan')}>查看后续学习目标</button>}<button className="button" disabled={disabled} onClick={()=>void chooseLesson(lessonId,true)}><RotateCcw size={17}/>再练一遍</button></div>{index===lessons.length-1&&<p className="line-note">你已完成这批体验课。完整半年课程仍需扩充，闯关完成不能代替 TOPIK 水平评定。</p>}</div>:
 isQuiz?<><div className="dialogue-body quiz-body"><div className="speaker"><Headphones size={19}/>听懂第 {quizStep+1} 句，共 2 句</div><p className="korean" lang="ko">{q.line.ko}</p><p className="translation">这句在当前对话中是什么意思？</p><button className="button" style={{marginTop:18}} onClick={()=>void play(q.line.audio)}><Volume2 size={17}/>再听一遍</button></div><div className="choices">{q.options.map((o,i)=><button key={o} disabled={busy} className={'choice '+(selected===i?(isCorrect?'correct':'wrong'):'')} onClick={()=>setAnswers(a=>{const next=[...a];next[quizStep]=i;return next;})}><span className="choice-letter">{String.fromCharCode(65+i)}</span>{o}{selected===i&&isCorrect&&<Check size={18}/>}</button>)}</div>{selected!==undefined&&<p className="answer-feedback" role="status">{isCorrect?'理解正确。':`还不太对。${q.line.note} 再选一次。`}</p>}<div className="card-controls"><button className="button subtle" disabled={busy} onClick={()=>{setCursor(0);setAnswers([]);setQuizStep(0);stopAudio();}}>回到对话</button><button className="button primary" disabled={!isCorrect||disabled} onClick={()=>{stopAudio();if(quizStep===0)setQuizStep(1);else void complete();}}>{busy?'保存中…':quizStep===0?'再听一句':'完成本关'}<ArrowRight size={17}/></button></div></>:
 <><div className="dialogue-body"><div className="speaker"><span className="avatar" aria-hidden="true">{line.speakerIndex===0?'가':'나'}</span>{lesson.roles[line.speakerIndex]}<span className="speaker-voice">SunHi</span></div><p className="korean" lang="ko">{line.ko}</p><p className={'translation '+(!meaning?'hidden-translation':'')}>{meaning?line.zh:'先听一遍，再试着理解。'}</p><p className="line-note">{meaning?line.note:'需要提示时，可以显示中文或点开下面的词语。'}</p></div><div className="card-controls"><div className="control-group"><button className="button" onClick={()=>playing?stopAudio():void play(line.audio)} aria-label={playing?'暂停语音':'播放 SunHi 原音'}>{playing?<Pause size={18}/>:<Volume2 size={18}/>}<span>{playing?'暂停':'听原音'}</span></button><button className="button subtle speech-speed" aria-label="切换播放速度" onClick={()=>{const next=rate===1?.8:1;setRate(next);if(audio.current)audio.current.playbackRate=next;}}>{rate===1?'1×':'0.8×'}</button><button className="button subtle" onClick={()=>setMeaning(!meaning)}>{meaning?'藏中文':'看中文'}</button></div><div className="control-group"><button className="button" aria-label="上一句" disabled={!cursor||busy} onClick={()=>{setCursor(cursor-1);setWord(null);stopAudio();}}><ChevronLeft size={18}/></button><button className="button primary" disabled={disabled} onClick={()=>void nextLine()}>{busy?'保存中…':cursor===lesson.lines.length-1?'听懂了，闯关':'懂了，下一句'}<ArrowRight size={17}/></button></div></div></>}
 </div>
 {audioError&&<p className="error-state" role="alert">{audioError}</p>}
 {!done&&!isQuiz&&<><div className="word-strip"><BookOpen size={17}/>本句词语{line.words.map(w=><button key={w.id} className={'word-chip '+(word?.id===w.id?'selected':'')} lang="ko" aria-pressed={word?.id===w.id} onClick={()=>setWord(word?.id===w.id?null:w)}>{w.term}</button>)}</div>{word&&<div className="word-detail"><div className="overview-row"><div><strong lang="ko">{word.term}</strong><span>{word.zh}</span></div><button className="button" aria-label={'播放单词 '+word.term} onClick={()=>void play(word.audio)}><Volume2 size={18}/></button></div><p>这里显示原形及本句用法。句子中的助词、时态和敬语会使词形发生变化。</p><a className="dictionary-link" href="https://krdict.korean.go.kr/chi/mainAction" target="_blank" rel="noreferrer">在国立国语院韩中词典核对</a></div>}</>}
 {done&&lesson.stage===5&&<div className="writing"><div className="overview-row"><h3>轮到你来回应</h3><span className="muted">书面表达 · 可选</span></div><p className="muted">围绕「{lesson.title}」，用韩语写一段 150–250 字的回复：提出观点，给出理由，并说明限制。这是练习，不自动评定 TOPIK 等级。</p><textarea className="text-answer" aria-label="我的韩语回复" lang="ko" value={draft} maxLength={4000} onChange={e=>{setDraft(e.target.value);draftTouched.current=true;setDraftSaved(false);}} placeholder="제 생각에는…"/><div className="overview-row"><span className="muted">{draft.length} 字 {draftSaved?'· 已存云端':''}</span><div className="control-group"><button className="button subtle" disabled={busy} onClick={()=>{setDraft(record?.draft??'');setDraftRevision(record?.draft_revision??0);draftTouched.current=false;setDraftSaved(false);}}>读取云端回复</button><button className="button" disabled={disabled||!draft.trim()} onClick={()=>void saveDraft()}>保存回复</button></div></div><details className="beginner-help"><summary>写完后自查</summary><p>观点是否明确？每个理由是否有例子？有无过度概括？主语、助词、时态和书面语尾是否一致？本功能只保存回复，尚未提供教师批改。</p></details></div>}
 <p className="hint">听一句，懂一句，再接下一句。</p><div className="bottom-stats"><span><strong>{counts.completed}</strong>/{lessons.length} 关完成</span><span><strong>{counts.words}</strong>/{totalWords} 词条接触</span><span><strong>{counts.sentences}</strong>/{totalSentences} 独立句学过</span></div><p className="coverage-note">首批对话课 · 学过不等于掌握，半年完整课程待扩充。</p>
 </section></main>
 <dialog ref={dialog} className="sheet" onClose={()=>setPanel(null)} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setPanel(null);}}}><div className="sheet-head"><h2>{panel==='lessons'?'你的对话旅程':panel==='plan'?'半年冲刺，逐步验证':'韩文，从拼成一个音节开始'}</h2><button className="button subtle" aria-label="关闭" onClick={()=>setPanel(null)}><X size={21}/></button></div>
 {panel==='lessons'&&<>{stages.map((s,i)=><section key={s} className="course-section"><h3><span className="muted">0{i+1}</span> {s}</h3><div className="lesson-list">{lessons.map((l,n)=>l.stage===i?<button className={'lesson-item '+(lesson.id===l.id?'active':'')} key={l.id} disabled={!unlocked(n)||disabled} onClick={()=>void chooseLesson(l.id)}><span><strong>{String(n+1).padStart(2,'0')} · {l.title}</strong><span className="muted block">{l.lines.length} 句对话</span></span>{progress.rows.find(r=>r.lesson_id===l.id)?.completed_at?<Check size={19}/>:!unlocked(n)?<Lock size={17}/>:<ArrowRight size={17}/>}</button>:null)}</div></section>)}</>}
 {panel==='plan'&&<><p>目标是半年内冲刺 TOPIK 6。每天投入 4 小时以上，也需要根据记忆保持率和阶段测评调整速度。</p><div className="plan-note"><strong>当前可学：36 关 · 216 条对话 · {totalSentences} 个去重独立句 · {totalWords} 个核心词条</strong><p>这是覆盖六个主题阶段的首批体验课，并非完整的半年课程。词条包含单词、助词及常用搭配，按原形文字去重；下表是完整课程的设计目标，不是官方词汇门槛，也不是现有内容数量。</p></div><div className="plan-grid">{targets.map(t=><div className="plan-cell" key={t[0]}><span className="eyebrow">{t[0]}</span><strong>{t[1]}</strong><span className="muted">累计目标：{t[2]} 词条 / {t[3]} 句</span></div>)}</div><h3 className="section-title">每天 4 小时，围绕对话练</h3><p>60 分钟听音与跟读 · 90 分钟新对话和词句理解 · 40 分钟隔天复述 · 50 分钟阅读、改写和书面回应。每周安排整段回听，按掌握情况减少或增加新内容。</p><h3 className="section-title">达到目标，要靠测评确认</h3><p>每月用限时听力、阅读和写作检验，而不是只看闯关数。TOPIK II 纸笔考试 6 级为 230–300 分；机考评分尺度不同。后期需要完整真题训练及写作批改，本首批课程尚不包含整套模考。</p><p><a href="https://www.niied.go.kr/web/NIIED/contents/niiedEng/eng_topikOverview" target="_blank" rel="noreferrer">查看 NIIED 官方考试说明</a></p><h3 className="section-title">内容与发音</h3><p>对话为原创韩中学习内容，已做本轮逐句语义检查。全部句子和词条使用 SunHi 神经语音。独立韩中审校及逐条人工听审尚未完成，不能将其视为已获教师认证的完整 TOPIK 6 课程。</p></>}
 {panel==='hangul'&&<><p>韩文按音节组合。<strong lang="ko">한 = ㅎ + ㅏ + ㄴ</strong>：开头辅音、元音、结尾收音。<strong lang="ko">아</strong> 的开头 ㅇ 不发音；收音位置的 ㅇ 发鼻音。</p><div className="plan-note">点下面的字母，听它组成的示例音节。辅音用「辅音 + ㅏ」演示，例如 ㄱ 的按钮播放 가，不是字母名称 기역。</div>{[['基本元音',0,10],['基本辅音',10,24],['紧音',24,29],['复合元音',29,40]].map(([title,start,end])=><section className="course-section" key={title}><h3>{title}</h3><div className="hangul-table">{hangul.slice(Number(start),Number(end)).map(h=><button key={h.letter} className="button" onClick={()=>void play(h.audio)} aria-label={`${h.letter} 的示例音节 ${h.syllable}`}><strong lang="ko">{h.letter}</strong><small lang="ko">{h.syllable}</small></button>)}</div></section>)}<p className="muted">收音主要归为七类音，且会发生连音、鼻音化、紧音化等变化。先听完整单词和句子，不用中文谐音代替韩文发音。这里是拼读速查，完整发音训练仍需扩充。</p></>}
 </dialog></>;
}
