"""Select source dialogues for coverage, then order by linguistic difficulty.

No sentences are generated by substitution. Every selected exchange retains
the NIKL example and sense identifiers. Segmentation is retained for review.
"""
import collections
import hashlib
import json
import pathlib
import re
from kiwipiepy import Kiwi

ROOT = pathlib.Path(__file__).resolve().parents[1]
CACHE = ROOT / '.sites-runtime/corpus'
LEVEL = {'초급': 0, '중급': 1, '고급': 2, '없음': 3}
LEXICAL = {'명사', '대명사', '수사', '동사', '형용사', '부사', '관형사', '감탄사', '보조 동사', '보조 형용사', '의존 명사'}
TAG_POS = {'NNG': {'명사'}, 'NP': {'대명사'}, 'NR': {'수사'}, 'NNB': {'의존 명사', '명사'},
           'VV': {'동사'}, 'VA': {'형용사'}, 'VX': {'보조 동사', '보조 형용사', '동사', '형용사'},
           'MAG': {'부사'}, 'MAJ': {'부사'}, 'MM': {'관형사'}, 'IC': {'감탄사'}}


def sentence_key(s):
    return re.sub(r'[\s.!?。？！]', '', s)


def main():
    dictionary = json.loads((CACHE / 'nikl-dictionary.json').read_text())
    source = json.loads((CACHE / 'nikl-dialogues.json').read_text())
    byterm = collections.defaultdict(list)
    for e in dictionary:
        if e['pos'] in LEXICAL and re.fullmatch('[가-힣]+', e['term']):
            byterm[e['term']].append(e)
    for entries in byterm.values():
        entries.sort(key=lambda e: (LEVEL[e['level']], int(e['id'])))
    source = [d for d in source if d['level'] != '없음' and d['term'] in byterm
              and len(d['lines']) == 2 and all(len(s.split()) >= 2 for s in d['lines'])]
    print('Candidate source dialogues:', len(source), flush=True)
    texts = list(dict.fromkeys(s for d in source for s in d['lines']))
    kiwi = Kiwi(num_workers=6)
    analysed = {}
    for i, (text, tokens) in enumerate(zip(texts, kiwi.tokenize(texts))):
        lexemes, forms = {}, []
        for j, token in enumerate(tokens):
            tag = token.tag.split('-')[0]
            term = token.lemma
            merged = None
            # Recombine noun + derivational suffix into its dictionary lemma.
            if tag in {'XSV', 'XSA'} and j and tokens[j-1].tag.startswith(('NN', 'XR', 'MAG')):
                compound = tokens[j-1].form + token.form + '다'
                if compound in byterm:
                    merged = compound
                    lexemes.pop(tokens[j-1].lemma, None)
            candidates = byterm.get(merged or term, [])
            candidates = [e for e in candidates if merged or e['pos'] in TAG_POS.get(tag, set())]
            if candidates:
                lexemes[merged or term] = candidates[0]['id']
            forms.append({'form': token.form, 'tag': tag, 'lemma': merged or term,
                          'start': token.start, 'length': token.len,
                          'entryIds': [e['id'] for e in candidates]})
        analysed[text] = {'tokens': forms, 'words': lexemes}
        if i % 4000 == 0:
            print('Segmented', i, '/', len(texts), flush=True)
    foundation = json.loads((ROOT / 'content/foundation.json').read_text())
    old_sentences = {sentence_key(s['ko']) for l in foundation for s in l['lines']}
    old_words = {w['term'] for l in foundation for s in l['lines'] for w in s['words']}
    eligible, seen = [], set()
    for d in source:
        keys = {sentence_key(s) for s in d['lines']}
        if len(keys) < 2 or keys & old_sentences:
            continue
        pair = tuple(d['lines'])
        if pair in seen:
            continue
        seen.add(pair)
        words = {w for s in d['lines'] for w in analysed[s]['words']}
        # Avoid associating a headword that the analyser cannot locate in the exchange.
        if d['term'] not in words:
            continue
        d['words'] = sorted(words)
        grades = [LEVEL[byterm[w][0]['level']] for w in words]
        length = sum(len(s.split()) for s in d['lines']) / 2
        endings = [t for s in d['lines'] for t in analysed[s]['tokens'] if t['tag'] in {'EC', 'ETM', 'ETN'}]
        d['difficulty'] = round(length * .28 + sum(grades) / max(len(grades), 1) * 2.5 + len(endings) * .18, 3)
        eligible.append(d)
    eligible.sort(key=lambda d: (LEVEL[d['level']], d['difficulty'], d['id']))
    # First cover different high-utility headwords. Repeated sentences are never
    # accepted to satisfy the independent sentence target.
    chosen, learned_words, used_sentences, used_heads = [], set(old_words), set(old_sentences), set()
    quotas = {'초급': 1100, '중급': 1450, '고급': 1450}
    pools = [[d for d in eligible if d['level'] == level] for level in quotas]
    for pool in pools:
        selected_in_level = 0
        for d in pool:
            if d['term'] in used_heads:
                continue
            keys = {sentence_key(s) for s in d['lines']}
            if keys & used_sentences:
                continue
            chosen.append(d)
            learned_words.update(d['words'])
            used_sentences.update(keys)
            used_heads.add(d['term'])
            selected_in_level += 1
            if selected_in_level >= quotas[d['level']]:
                break
    if len(used_sentences) < 8200 or len(learned_words) < 6200:
        for d in sorted(eligible, key=lambda d: (-len(set(d['words']) - learned_words), d['difficulty'])):
            keys = {sentence_key(s) for s in d['lines']}
            if keys & used_sentences:
                continue
            chosen.append(d)
            learned_words.update(d['words'])
            used_sentences.update(keys)
            if len(used_sentences) >= 8200 and len(learned_words) >= 6200:
                break
    assert len(used_sentences) >= 8000 and len(learned_words) >= 6000
    chosen.sort(key=lambda d: (d['difficulty'], d['category'], d['id']))
    selected_texts = {s for d in chosen for s in d['lines']}
    (CACHE / 'selected-dialogues.json').write_text(json.dumps(chosen, ensure_ascii=False, separators=(',', ':')))
    (CACHE / 'selected-morphology.json').write_text(json.dumps({s: analysed[s] for s in selected_texts}, ensure_ascii=False, separators=(',', ':')))
    (CACHE / 'selected-dictionary.json').write_text(json.dumps([e for e in dictionary if e['term'] in learned_words], ensure_ascii=False, separators=(',', ':')))
    report = {'candidateDialogues': len(source), 'eligibleDialogues': len(eligible), 'selectedDialogues': len(chosen),
              'uniqueSentencesIncludingFoundation': len(used_sentences), 'uniqueLexicalEntriesIncludingFoundation': len(learned_words),
              'dictionaryTranslations': 'NIKL official Chinese senses', 'sentenceTranslations': 'pending',
              'morphologicalAnalysis': 'Kiwi 0.23.2; automatic, requires contextual review'}
    (CACHE / 'selection-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps(report, ensure_ascii=False), flush=True)


if __name__ == '__main__':
    main()
